// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2lx_F3JVsPVCWL-8U_ORmaLSbHOp3g2E',
    appId: '1:324237130014:web:36f93972e9945acefb310f',
    messagingSenderId: '324237130014',
    projectId: 'inventory-management-app-5da08',
    authDomain: 'inventory-management-app-5da08.firebaseapp.com',
    storageBucket: 'inventory-management-app-5da08.firebasestorage.app',
    measurementId: 'G-NY48TJWNNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQFAQNadHEFjwgpkjGLC6PK7Cc4ZY0u6g',
    appId: '1:324237130014:android:499b2c8e7ea61e23fb310f',
    messagingSenderId: '324237130014',
    projectId: 'inventory-management-app-5da08',
    storageBucket: 'inventory-management-app-5da08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR0KiHwcpF9NNpDQHZuGEozjGQo5tJsFo',
    appId: '1:324237130014:ios:a88da7fb97a8f061fb310f',
    messagingSenderId: '324237130014',
    projectId: 'inventory-management-app-5da08',
    storageBucket: 'inventory-management-app-5da08.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR0KiHwcpF9NNpDQHZuGEozjGQo5tJsFo',
    appId: '1:324237130014:ios:a88da7fb97a8f061fb310f',
    messagingSenderId: '324237130014',
    projectId: 'inventory-management-app-5da08',
    storageBucket: 'inventory-management-app-5da08.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2lx_F3JVsPVCWL-8U_ORmaLSbHOp3g2E',
    appId: '1:324237130014:web:b87312dc3660d51ffb310f',
    messagingSenderId: '324237130014',
    projectId: 'inventory-management-app-5da08',
    authDomain: 'inventory-management-app-5da08.firebaseapp.com',
    storageBucket: 'inventory-management-app-5da08.firebasestorage.app',
    measurementId: 'G-5M2L8VLBS3',
  );
}
